---
image: "buluma/github-action-molecule:5.0.7"

variables:
  PY_COLORS: 1

molecule:
  script:
    - if [ -f tox.ini ] ; then tox ; fi
    - if [ ! -f tox.ini ] ; then molecule test ; fi
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  parallel:
    matrix:
      - image: "debian-systemd"
        tag: "latest"

galaxy:
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} buluma ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG != null
